# Generated by Django 5.1.6 on 2025-03-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(verbose_name='Reminder Date'),
        ),
    ]
