# Generated by Django 5.1.6 on 2025-03-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_catagory_alter_reminder_options_alter_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='catagories',
            field=models.ManyToManyField(to='my_app.catagory'),
        ),
    ]
